language: python
python:
 # - "2.6"
  - "2.7"
  #- "3.3"
  #- "3.4"
  #- "pypy"
#sudo: false
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then travis_retry pip install -r requirements26.txt; fi
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install coverage python-coveralls
script: nosetests --with-coverage --cover-erase
after_success: coveralls
